#auth0:
#  domain: '%env(AUTH0_DOMAIN)%'
#  client_id: '%env(AUTH0_CLIENT_ID)%'
#  client_secret: '%env(AUTH0_CLIENT_SECRET)%'
#  redirect_uri: '%env(AUTH0_REDIRECT_URI)%'
#  audience: '%env(AUTH0_AUDIENCE)%'
#  scone: 'openid offline_access read:users'
#  persist_id_token: true
#  persist_access_token: true
#  persist_refresh_token: true