security:
    providers:
        symfony_security_provider:
            id:
                security_user_provider

    encoders:
        App\Symfony\Security\SessionAuth\SessionAuthUser:
            algorithm: bcrypt
            cost: 12

    firewalls:
        refresh:
            pattern:  ^/api/token/refresh
            provider: symfony_security_provider
            anonymous: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            stateless: true
            anonymous: false
            pattern: ^/api
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            provider: symfony_security_provider

        main:
            anonymous: ~
            logout:
                path: /logout
                target: /
            guard:
                authenticators:
                    - App\Symfony\Security\SessionAuth\LoginFormAuthenticator
            provider: symfony_security_provider

    access_control:
        - { path: ^/activation/confirm/, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['GET', 'PATCH']}
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/, roles: [ROLE_ADMIN], methods: ['POST', 'DELETE', 'PATCH', 'PUT']}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin_panel, roles: [ROLE_ADMIN] }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }
