login:
  path:       /login
  controller: App\Interfaces\Web\Controller\SecurityController::login
  methods:    GET|POST

logout:
  path:       /logout
  methods:    GET

api_login_check:
  path: /api/login_check