services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{Tests,Kernel.php}'

    App\Interfaces\Web\Controller\:
        resource: '../src/Interfaces/Web/Controller'
        tags: ['controller.service_arguments']

    command_handlers:
        public: true
        namespace: App\Application\Handler\
        resource: '../src/Application/Handler/*'
        tags: [command_handler]

    api_exception_subscriber:
        class: App\Infrastructure\Listeners\ApiExceptionSubscriber
        arguments: []
        tags:
            - { name: kernel.event_subscriber}

    security_user_provider:
        class: App\Domain\Security\Symfony\SessionAuth\SessionAuthUserProvider

    # Auth0
    web_service_user_provider:
        class: App\Domain\Security\Auth0\User\WebServiceUserProvider
        arguments: ["@jwt_auth.auth0_service"]

    # Auth0
    Auth0\SDK\Auth0:
        class: Auth0\SDK\Auth0
        arguments: ['%auth0%']