services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{Tests,Kernel.php}'

    App\Interfaces\Web\Controller\:
        resource: '../src/Interfaces/Web/Controller'
        tags: ['controller.service_arguments']

    command_handlers:
        public: true
        namespace: App\Application\Handler\
        resource: '../src/Application/Handler/*'
        tags: [command_handler]

    # Auth0
    web_service_user_provider:
        class: App\Domain\Security\User\WebServiceUserProvider
        arguments: ["@jwt_auth.auth0_service"]